config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root "kittens#index"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, format: {with: /\A[A-Z]+\z/i }, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types(:danger)

end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kittens}
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to kittens_path, notice: "New kitting created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    if @kitten.update(kitten_params)
      redirect_to kittens_path, notice: "Task failed successfully!"
    else 
      render :edit, status: :unprocessable_entity
    end    
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.delete
    flash[:notice] = "Kitten killed!"

    redirect_to kittens_path
  end

  private

  def kitten_params 
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/kittens/_form.html.erb
<%= form_with(model: kitten) do |f| %>
  <%= render "errors", object: kitten %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <br>
  <div>
    <%= f.label :age %>
    <%= f.select :age, 1..25 %>
  </div>
  <br>
  <div>
    <%= f.label :cuteness %>
    <%= f.select :cuteness, 1..10 %>
  </div>
  <br>
  <div>
    <%= f.label :softness %>
    <%= f.select :softness, 1..10 %>
  </div>
  <br>
  <%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit kitten</h1>

<%= render "form", kitten: @kitten %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<% @kittens.each do |kitten| %>
   <div>
      <%= link_to kitten.name, kitten_path(kitten) %> 
      <%= link_to "Kill Kitten", kitten_path(kitten), data: { turbo_method: :delete } %>
   </div>
<% end %>
<br>

<%= link_to "New Kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Create new kitten</h1>

<%= render "form", kitten: @kitten %>

app/views/kittens/show.html.erb
<h1>Kitten</h1>

<div><%= @kitten.name %></div>
<div><%= @kitten.age %></div>

<div><%= link_to "Kill Kitten", kitten_path(@kitten), data: { turbo_method: :delete } %></div>
<div><%= link_to "Edit Kitten", edit_kitten_path(@kitten) %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= button_to "Home", kittens_path, method: :get %>
    <div class="content">
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>